// packages/react/src/components/select/Select.tsx
import { Portal } from "@ark-ui/react/portal";
import { Select as ArkSelect, createListCollection, type ListCollection } from "@ark-ui/react/select";
import type { SelectProps as CoreSelectProps } from "@temporal-ui/core/select";
import React, { forwardRef } from "react";
import { Field } from "../field";
import { SelectContent, type SelectItem } from "./SelectContent";
import { SelectTrigger } from "./SelectTrigger";

export interface SelectProps<M = unknown>
	extends CoreSelectProps<M, React.ReactNode>,
		Omit<React.SelectHTMLAttributes<HTMLSelectElement>, "defaultValue" | "value" | "onBlur"> {
	collection?: ListCollection<SelectItem<M>>;
}

export const Select = forwardRef<HTMLSelectElement, SelectProps>((props, ref) => {
	const {
		label,
		hint,
		error,
		required,
		readOnly,
		disabled,
		classes,
		testId,
		collection,
		data,
		placeholder,
		indicator,
		portal,
		deselectable,
		defaultValue,
		value,
		className,
		onBlur,
		onValueChange,
		renderItem,
		startSection,
		...rest
	} = props;

	const listCollection = React.useMemo(
		() =>
			collection ??
			createListCollection({
				items: data ?? [],
				groupBy: (item) => item.group ?? "",
				isItemDisabled: (item) => item.disabled ?? false,
			}),
		[data, collection],
	);

	return (
		<Field
			hint={hint}
			classes={classes}
			required={required}
			readOnly={readOnly}
			error={error}
			disabled={disabled}
			testId={testId ? `${testId}-field` : undefined}
		>
			<ArkSelect.Root
				data-testid={testId ? `${testId}--root` : undefined}
				collection={listCollection}
				deselectable={deselectable}
				value={value ? [value] : undefined}
				defaultValue={defaultValue ? [defaultValue] : undefined}
				disabled={disabled}
				invalid={!!error}
				required={required}
				readOnly={readOnly}
				onFocusOutside={onBlur}
				onValueChange={onValueChange ? (details) => onValueChange?.(details.value[0]) : undefined}
				positioning={{
					offset: {
						mainAxis: 0,
					},
				}}
			>
				<ArkSelect.Label>{label}</ArkSelect.Label>
				<SelectTrigger
					className={className}
					testId={testId}
					placeholder={placeholder}
					indicator={indicator}
					renderItem={renderItem}
					startSection={startSection}
				/>
				{portal && (
					<Portal>
						<SelectContent
							testId={testId}
							collection={listCollection}
							renderItem={renderItem}
						/>
					</Portal>
				)}
				{!portal && (
					<SelectContent
						testId={testId}
						collection={listCollection}
						renderItem={renderItem}
					/>
				)}
				<ArkSelect.HiddenSelect
					ref={ref}
					data-testid={testId ? `${testId}--input` : undefined}
					{...rest}
				/>
			</ArkSelect.Root>
		</Field>
	);
});

// packages/solid/src/components/select/Select.tsx
import { Select as ArkSelect, createListCollection, type ListCollection } from "@ark-ui/solid/select";
import type { SelectProps as CoreSelectProps } from "@temporal-ui/core/select";
import { mergeProps, splitProps, type JSX } from "solid-js";
import { Portal } from "solid-js/web";
import { Field } from "../field";
import { SelectContent, type SelectItem } from "./SelectContent";
import { SelectTrigger } from "./SelectTrigger";
import type { HTMLProps } from "@ark-ui/solid";

export interface SelectProps<M> extends CoreSelectProps<M, JSX.Element>, Omit<HTMLProps<'select'>, 'onBlur' | 'defaultValue' | 'value'> {
	collection?: ListCollection<SelectItem<M>>;
	class?: string;
}

export function Select<M = unknown>(_props: SelectProps<M>) {
	const [fieldProps, rootProps, triggerProps, selectProps] = splitProps(
		mergeProps({ portal: true }, _props),
		["label", "hint", "error", "required", "readOnly", "disabled", "classes", "testId"],
		["collection", "data", "portal", "deselectable", "defaultValue", "value", "onValueChange", "onBlur"],
		["className", "class", "placeholder", "indicator", "renderItem", "startSection"],
	);

	const listCollection = () =>
		rootProps.collection ??
		createListCollection({
			items: rootProps.data ?? [],
			groupBy: (item) => item.group ?? "",
			isItemDisabled: (item) => item.disabled ?? false,
		});

	return (
		<Field
			{...fieldProps}
			testId={fieldProps.testId ? `${fieldProps.testId}-field` : undefined}
		>
			<ArkSelect.Root
				{...rootProps}
				data-testid={fieldProps.testId ? `${fieldProps.testId}--root` : undefined}
				collection={listCollection()}
				disabled={fieldProps.disabled}
				invalid={!!fieldProps.error}
				required={fieldProps.required}
				readOnly={fieldProps.readOnly}
				value={rootProps.value ? [rootProps.value] : undefined}
				defaultValue={rootProps.defaultValue ? [rootProps.defaultValue] : undefined}
				onValueChange={(details) => rootProps.onValueChange?.(details.value[0])}
				onFocusOutside={rootProps.onBlur}
				positioning={{
					offset: {
						mainAxis: 0,
					},
				}}
			>
				<SelectTrigger
					{...triggerProps}
					testId={fieldProps.testId}
				/>
				{rootProps.portal ? (
					<Portal>
						<SelectContent
							testId={fieldProps.testId}
							collection={listCollection()}
							renderItem={triggerProps.renderItem}
						/>
					</Portal>
				) : (
					<SelectContent
						testId={fieldProps.testId}
						collection={listCollection()}
						renderItem={triggerProps.renderItem}
					/>
				)}
				<ArkSelect.HiddenSelect
					{...selectProps}
					data-testid={fieldProps.testId ? `${fieldProps.testId}--input` : undefined}
				/>
			</ArkSelect.Root>
		</Field>
	);
}
