// packages/react/src/components/data-table/DataTable.tsx
import { flexRender, getCoreRowModel, useReactTable, type TableOptions } from "@tanstack/react-table";
import type { BaseComponent } from "@temporal-ui/core/base";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../table";

export interface DataTableProps<TData>
	extends BaseComponent<React.ReactNode>,
		Omit<TableOptions<TData>, "getCoreRowModel"> {
	getCoreRowModel?: TableOptions<TData>["getCoreRowModel"];
}

export function DataTable<TData>({ testId, ...props }: DataTableProps<TData>) {
	const table = useReactTable({
		getCoreRowModel: getCoreRowModel(),
		...props,
	});

	return (
		<div
			data-scope="data-table"
			data-part="container"
			data-testid={testId ? `${testId}--container` : undefined}
		>
			<Table testId={testId ? `${testId}--table` : undefined}>
				<TableHeader testId={testId ? `${testId}--thead` : undefined}>
					{table.getHeaderGroups().map((headerGroup) => (
						<TableRow
							key={headerGroup.id}
							testId={testId ? `${testId}--tr` : undefined}
						>
							{headerGroup.headers.map((header) => {
								return (
									<TableHead
										key={header.id}
										testId={testId ? `${testId}--th` : undefined}
									>
										{header.isPlaceholder
											? null
											: flexRender(header.column.columnDef.header, header.getContext())}
									</TableHead>
								);
							})}
						</TableRow>
					))}
				</TableHeader>
				<TableBody testId={testId ? `${testId}--tbody` : undefined}>
					{table.getRowModel().rows?.length ? (
						table.getRowModel().rows.map((row) => (
							<TableRow
								key={row.id}
								data-state={row.getIsSelected() && "selected"}
								testId={testId ? `${testId}--tr` : undefined}
							>
								{row.getVisibleCells().map((cell) => (
									<TableCell
										key={cell.id}
										testId={testId ? `${testId}--td` : undefined}
									>
										{flexRender(cell.column.columnDef.cell, cell.getContext())}
									</TableCell>
								))}
							</TableRow>
						))
					) : (
						<TableRow testId={testId ? `${testId}--row` : undefined}>
							<TableCell
								colSpan={props.columns.length}
								className="h-24 text-center"
							>
								No results.
							</TableCell>
						</TableRow>
					)}
				</TableBody>
			</Table>
		</div>
	);
}

// packages/solid/src/components/data-table/DataTable.tsx
import { createSolidTable, flexRender, getCoreRowModel, getFilteredRowModel, type TableOptions } from "@tanstack/solid-table";
import type { BaseComponent } from "@temporal-ui/core/base";
import { For, type JSX } from "solid-js";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../table";

export interface DataTableProps<TData>
	extends BaseComponent<JSX.Element>,
		Omit<TableOptions<TData>, "getCoreRowModel"> {
	getCoreRowModel?: TableOptions<TData>["getCoreRowModel"];
}

export function DataTable<TData>(props: DataTableProps<TData>) {
	const table = createSolidTable({
		getCoreRowModel: getCoreRowModel(),
		getFilteredRowModel: getFilteredRowModel(),
		...props,
		get data() {
			return props.data;
		},
	});

	return (
		<div
			data-scope="data-table"
			data-part="container"
			data-testid={props.testId ? `${props.testId}--container` : undefined}
		>
			<Table testId={props.testId ? `${props.testId}--table` : undefined}>
				<TableHeader testId={props.testId ? `${props.testId}--thead` : undefined}>
					<For each={table.getHeaderGroups()}>
						{(headerGroup) => (
							<TableRow testId={props.testId ? `${props.testId}--tr` : undefined}>
								<For each={headerGroup.headers}>
									{(header) => (
										<TableHead testId={props.testId ? `${props.testId}--th` : undefined}>
											{header.isPlaceholder
												? null
												: flexRender(header.column.columnDef.header, header.getContext())}
										</TableHead>
									)}
								</For>
							</TableRow>
						)}
					</For>
				</TableHeader>
				<TableBody testId={props.testId ? `${props.testId}--tbody` : undefined}>
					{table.getRowModel().rows?.length ? (
						<For each={table.getRowModel().rows}>
							{(row) => (
								<TableRow
									data-state={row.getIsSelected() && "selected"}
									testId={props.testId ? `${props.testId}--tr` : undefined}
								>
									<For each={row.getVisibleCells()}>
										{(cell) => (
											<TableCell testId={props.testId ? `${props.testId}--td` : undefined}>
												{flexRender(cell.column.columnDef.cell, cell.getContext())}
											</TableCell>
										)}
									</For>
								</TableRow>
							)}
						</For>
					) : (
						<TableRow testId={props.testId ? `${props.testId}--row` : undefined}>
							<TableCell
								colSpan={props.columns.length}
								className="h-24 text-center"
							>
								No results.
							</TableCell>
						</TableRow>
					)}
				</TableBody>
			</Table>
		</div>
	);
}
