// packages/solid/src/components/radio-group/RadioGroup.tsx
import { RadioGroup as ArkRadioGroup } from "@ark-ui/solid/radio-group";
import type { RadioGroupProps as CoreRadioGroupProps } from "@temporal-ui/core/radio-group";
import { cx } from "@temporal-ui/core/utils/cx";
import type { JSX } from "solid-js";
import { Index, splitProps } from "solid-js";

export interface RadioGroupProps extends CoreRadioGroupProps<JSX.Element> {}

export type { RadioGroupItem } from "@temporal-ui/core/radio-group";

export function RadioGroup(_props: RadioGroupProps) {
	const [fieldProps, groupProps] = splitProps(
		_props,
		["label", "hint", "error", "required", "readOnly", "disabled", "classes", "testId"],
		["items", "orientation", "defaultValue", "value", "onValueChange"],
	);

	return (
		<ArkRadioGroup.Root
			class={cx("field-root", fieldProps.classes?.root)}
			defaultValue={groupProps.defaultValue}
			value={groupProps.value}
			disabled={fieldProps.disabled}
			aria-required={fieldProps.required}
			readOnly={fieldProps.readOnly}
			onValueChange={(details) => groupProps.onValueChange?.(details.value)}
			orientation={groupProps.orientation}
			data-testid={fieldProps.testId ? `${fieldProps.testId}--group` : undefined}
		>
			{fieldProps.label && (
				<ArkRadioGroup.Label
					class={cx("field-label", fieldProps.classes?.label)}
					data-testid={fieldProps.testId ? `${fieldProps.testId}--label` : undefined}
				>
					{fieldProps.label}
				</ArkRadioGroup.Label>
			)}
			{fieldProps.hint && (
				<div
					class={cx("field-hint", fieldProps.classes?.hint)}
					aria-disabled={fieldProps.disabled}
					data-testid={fieldProps.testId ? `${fieldProps.testId}--hint` : undefined}
				>
					{fieldProps.hint}
				</div>
			)}
			<Index each={groupProps.items}>
				{(item, i) => (
					<ArkRadioGroup.Item
						value={item().value}
						disabled={item().disabled}
						invalid={!!fieldProps.error}
						data-testid={
							fieldProps.testId ? `${fieldProps.testId}--item-${i}` : undefined
						}
					>
						<ArkRadioGroup.ItemControl
							data-testid={
								fieldProps.testId
									? `${fieldProps.testId}--item-control-${i}`
									: undefined
							}
						/>
						<ArkRadioGroup.ItemText
							data-testid={
								fieldProps.testId
									? `${fieldProps.testId}--item-text-${i}`
									: undefined
							}
						>
							{item().label}
						</ArkRadioGroup.ItemText>
						<ArkRadioGroup.ItemHiddenInput
							data-testid={
								fieldProps.testId
									? `${fieldProps.testId}--item-input-${i}`
									: undefined
							}
						/>
					</ArkRadioGroup.Item>
				)}
			</Index>
			{fieldProps.error && (
				<div
					class={cx("field-error", fieldProps.classes?.error)}
					data-testid={fieldProps.testId ? `${fieldProps.testId}--error` : undefined}
				>
					{fieldProps.error}
				</div>
			)}
		</ArkRadioGroup.Root>
	);
}

// packages/react/src/components/radio-group/RadioGroup.tsx
import type { RadioGroupProps as CoreRadioGroupProps } from "@temporal-ui/core/radio-group";
import { RadioGroup as ArkRadioGroup } from "@ark-ui/react/radio-group";
import type React from "react";
import { cx } from "@temporal-ui/core/utils/cx";

export interface RadioGroupProps extends CoreRadioGroupProps<React.ReactNode> {}

export type { RadioGroupItem } from "@temporal-ui/core/radio-group";

export function RadioGroup(props: RadioGroupProps) {
	const {
		label,
		hint,
		error,
		disabled,
		classes,
		items,
		defaultValue,
		value,
		onValueChange,
		orientation,
		testId,
	} = props;

	return (
		<ArkRadioGroup.Root
			className={cx("field-root", classes?.root)}
			defaultValue={defaultValue}
			disabled={disabled}
			value={value}
			onValueChange={(details) => onValueChange?.(details.value)}
			orientation={orientation}
			readOnly={props.readOnly}
			aria-required={props.required}
			data-testid={testId ? `${testId}--root` : undefined}
		>
			{label && (
				<ArkRadioGroup.Label
					className={cx("field-label", classes?.label)}
					data-testid={testId ? `${testId}--label` : undefined}
				>
					{label}
				</ArkRadioGroup.Label>
			)}
			{hint && (
				<div
					className={cx("field-hint", classes?.hint)}
					aria-disabled={disabled}
					data-testid={testId ? `${testId}--hint` : undefined}
				>
					{hint}
				</div>
			)}
			<ArkRadioGroup.Indicator />
			{items.map((item, i) => (
				<ArkRadioGroup.Item
					key={item.value}
					value={item.value}
					disabled={item.disabled}
					invalid={!!error}
					data-testid={testId ? `${testId}--item-${i}` : undefined}
				>
					<ArkRadioGroup.ItemControl
						data-testid={testId ? `${testId}--item-control-${i}` : undefined}
					/>
					<ArkRadioGroup.ItemText
						data-testid={testId ? `${testId}--item-text-${i}` : undefined}
					>
						{item.label}
					</ArkRadioGroup.ItemText>
					<ArkRadioGroup.ItemHiddenInput
						data-testid={testId ? `${testId}--item-input-${i}` : undefined}
					/>
				</ArkRadioGroup.Item>
			))}
			{error && (
				<div
					className={cx("field-error", classes?.error)}
					data-testid={testId ? `${testId}--error` : undefined}
				>
					{error}
				</div>
			)}
		</ArkRadioGroup.Root>
	);
}
