// packages/solid/src/components/card/Card.tsx
import { type CardProps as CoreCardProps, cx } from "@temporal-ui/core";
import { children, type JSX } from "solid-js";

export interface CardProps extends CoreCardProps {
	children?: JSX.Element | JSX.Element[];
	style?: JSX.CSSProperties

}
export function Card(props: CardProps) {

	return (
		<div
			class={cx("card", props.class)}
			style={props.style}
		>
			{children(() => props.children)}
		</div>
	)
}

// packages/react/src/components/card/Card.tsx
import { type CardProps as CoreCardProps, cx } from "@temporal-ui/core";
import type React from "react";

export interface CardProps extends CoreCardProps {
	children?: React.ReactNode | React.ReactNode[];
	style?: React.CSSProperties;

}
export function Card(props: CardProps) {

	return (
		<div
			className={cx("card", props.class)}
			style={props.style}
		>
			{props.children}
		</div>
	)
}
