// packages/solid/src/components/menu/MenuCheckboxItem.tsx
import { Menu as ArkMenu } from "@ark-ui/solid/menu";
import { testId } from "@temporal-ui/core/utils/string";
import {  CheckIcon  } from '../icons';
import { splitProps, type ComponentProps } from "solid-js";
import type { MenuCheckboxItemProps as CoreMenuCheckboxItemProps } from "@temporal-ui/core/menu";

export interface MenuCheckboxItemProps extends CoreMenuCheckboxItemProps, ComponentProps<typeof ArkMenu.CheckboxItem> {}

export function MenuCheckboxItem(props: MenuCheckboxItemProps) {
	const [localProps, itemProps] = splitProps(props, ["className", "testId", "children"]);
	const tid = testId(localProps.testId);
	return (
		<ArkMenu.CheckboxItem
			{...itemProps}
			class={localProps.className}
			data-testid={tid("--checkbox-item")}
		>
			<div data-part="item-indicator-container">
				<ArkMenu.ItemIndicator data-testid={tid("--checkbox-item-indicator")}>
					<CheckIcon />
				</ArkMenu.ItemIndicator>
			</div>
			<ArkMenu.ItemText data-testid={tid("--checkbox-item-text")}>{localProps.children}</ArkMenu.ItemText>
		</ArkMenu.CheckboxItem>
	);
}

// packages/react/src/components/menu/MenuCheckboxItem.tsx
import type { MenuCheckboxItemProps as CoreMenuCheckboxItemProps } from "@temporal-ui/core/menu";
import { Menu as ArkMenu } from "@ark-ui/react/menu";
import type React from "react";
import {  CheckIcon  } from '../icons';
import { testId as testIdFn } from "@temporal-ui/core/utils/string";

export interface MenuCheckboxItemProps
	extends CoreMenuCheckboxItemProps,
		React.ComponentProps<typeof ArkMenu.CheckboxItem> {}

export function MenuCheckboxItem(props: MenuCheckboxItemProps) {
	const { testId, children, ...rest } = props;
	const tid = testIdFn(testId);

	return (
		<ArkMenu.CheckboxItem
			{...rest}
			data-testid={tid("--checkbox-item")}
		>
			<div data-part="item-indicator-container">
				<ArkMenu.ItemIndicator data-testid={tid("--checkbox-item-indicator")}>
					<CheckIcon />
				</ArkMenu.ItemIndicator>
			</div>
			<ArkMenu.ItemText data-testid={tid("--checkbox-item-text")}>{children}</ArkMenu.ItemText>
		</ArkMenu.CheckboxItem>
	);
}
