// packages/solid/src/components/menu/MenuItemGroup.tsx
import { Menu as ArkMenu } from "@ark-ui/solid/menu";
import { testId } from "@temporal-ui/core/utils/string";
import type { ComponentProps } from "solid-js";
import { Show, splitProps } from "solid-js";
import type { MenuItemGroupProps as CoreMenuItemGroupProps } from "@temporal-ui/core/menu";

export interface MenuItemGroupProps extends CoreMenuItemGroupProps, ComponentProps<typeof ArkMenu.ItemGroup> {}

export function MenuItemGroup(props: MenuItemGroupProps) {
	const [localProps, itemGroupProps] = splitProps(props, ["className", "testId", "label", "children"]);

	const tid = testId(localProps.testId);

	return (
		<ArkMenu.ItemGroup
			{...itemGroupProps}
			class={localProps.className}
			data-testid={tid("--group")}
		>
			<Show when={localProps.label}>
				<ArkMenu.ItemGroupLabel data-testid={tid("--label")}>{localProps.label}</ArkMenu.ItemGroupLabel>
			</Show>
			{localProps.children}
		</ArkMenu.ItemGroup>
	);
}

// packages/react/src/components/menu/MenuItemGroup.tsx
import type { MenuItemGroupProps as CoreMenuItemGroupProps } from "@temporal-ui/core/menu";
import { Menu as ArkMenu } from "@ark-ui/react/menu";
import type React from "react";
import { testId as testIdFn } from "@temporal-ui/core/utils/string";

export interface MenuItemGroupProps extends CoreMenuItemGroupProps, React.ComponentProps<typeof ArkMenu.ItemGroup> {}

export function MenuItemGroup(props: MenuItemGroupProps) {
	const { label, testId, children, ...restProps } = props;
	const tid = testIdFn(testId);

	return (
		<ArkMenu.ItemGroup
			{...restProps}
			data-testid={tid("--group")}
		>
			{label && <ArkMenu.ItemGroupLabel data-testid={tid("--label")}>{label}</ArkMenu.ItemGroupLabel>}
			{children}
		</ArkMenu.ItemGroup>
	);
}
