// packages/react/src/components/menu/Menu.tsx
import type { MenuProps as CoreMenuProps } from "@temporal-ui/core/menu";
import { Menu as ArkMenu } from "@ark-ui/react/menu";
import type React from "react";
import { Portal } from "@ark-ui/react/portal";

export interface MenuProps extends CoreMenuProps<React.ReactNode> {
	trigger: React.ReactNode;
}

export function Menu(props: MenuProps) {
	const { trigger, children, className, onSelect, closeOnSelect, testId, position } = props;

	return (
		<ArkMenu.Root
			onSelect={(details) => onSelect?.(details.value)}
			closeOnSelect={closeOnSelect}
			data-testid={testId ? `${testId}--root` : undefined}
			positioning={position}
		>
			<ArkMenu.Trigger
				data-testid={testId ? `${testId}--trigger` : undefined}
				asChild
			>
				{trigger}
			</ArkMenu.Trigger>
			<Portal>
				<ArkMenu.Positioner data-testid={testId ? `${testId}--positioner` : undefined}>
					<ArkMenu.Content
						className={className}
						data-testid={testId ? `${testId}--content` : undefined}
					>
						{children}
					</ArkMenu.Content>
				</ArkMenu.Positioner>
			</Portal>
		</ArkMenu.Root>
	);
}

// packages/solid/src/components/menu/Menu.tsx
import { Menu as ArkMenu } from "@ark-ui/solid/menu";
import type { MenuProps as CoreMenuProps } from "@temporal-ui/core/menu";
import type { JSX, ParentProps } from "solid-js";
import { Portal } from "solid-js/web";

export interface MenuProps extends CoreMenuProps<JSX.Element> {
	trigger: (props: ParentProps) => JSX.Element;
}

export function Menu(menuProps: MenuProps) {
	return (
		<ArkMenu.Root
			onSelect={(details) => menuProps.onSelect?.(details.value)}
			closeOnSelect={menuProps.closeOnSelect}
			positioning={menuProps.position}
			data-testid={menuProps.testId ? `${menuProps.testId}--root` : undefined}
		>
			<ArkMenu.Trigger
				asChild={(props) => menuProps.trigger(props())}
				data-testid={menuProps.testId ? `${menuProps.testId}--trigger` : undefined}
			/>
			<Portal>
				<ArkMenu.Positioner data-testid={menuProps.testId ? `${menuProps.testId}--positioner` : undefined}>
					<ArkMenu.Content
						class={menuProps.className}
						data-testid={menuProps.testId ? `${menuProps.testId}--content` : undefined}
					>
						{menuProps.children}
					</ArkMenu.Content>
				</ArkMenu.Positioner>
			</Portal>
		</ArkMenu.Root>
	);
}
