// packages/react/src/components/number-input/NumberInput.tsx
import type { NumberInputProps as CoreNumberInputProps } from "@temporal-ui/core/number-input";
import { NumberInput as ArkNumberInput } from "@ark-ui/react/number-input";
import type React from "react";
import { Field } from "../field";
import { ChevronDown, ChevronUp } from "lucide-react";
import { forwardRef } from "react";

export interface NumberInputProps
	extends CoreNumberInputProps<React.ReactNode>,
		Omit<React.InputHTMLAttributes<HTMLInputElement>, "max" | "min" | "step" | "defaultValue" | "value"> {}

export const NumberInput = forwardRef<HTMLInputElement, NumberInputProps>((props, ref) => {
	const {
		label,
		hint,
		error,
		required,
		readOnly,
		disabled,
		classes,
		startSection,
		min,
		max,
		step,
		testId,
		value,
		defaultValue,
		onValueChange,
		...rest
	} = props;
	return (
		<Field
			label={label}
			hint={hint}
			classes={classes}
			required={required}
			readOnly={readOnly}
			error={error}
			disabled={disabled}
			testId={testId ? `${testId}-field` : undefined}
		>
			<ArkNumberInput.Root
				min={min}
				max={max}
				step={step}
				value={value ? String(value) : undefined}
				defaultValue={defaultValue ? String(defaultValue) : undefined}
				onValueChange={(details) => onValueChange?.(details.valueAsNumber)}
				data-with-start-section={startSection ? true : undefined}
				data-testid={testId ? `${testId}--root` : undefined}
			>
				<ArkNumberInput.Control>
					{startSection && (
						<div
							data-scope={"number-input"}
							data-part={"start-section"}
							data-testid={testId ? `${testId}--start-section` : undefined}
						>
							{startSection}
						</div>
					)}
					<ArkNumberInput.Input
						ref={ref}
						{...rest}
						data-with-start-section={startSection ? true : undefined}
						data-testid={testId ? `${testId}--input` : undefined}
					/>
					<ArkNumberInput.IncrementTrigger>
						<ChevronUp size={16} />
					</ArkNumberInput.IncrementTrigger>
					<ArkNumberInput.DecrementTrigger>
						<ChevronDown size={16} />
					</ArkNumberInput.DecrementTrigger>
				</ArkNumberInput.Control>
			</ArkNumberInput.Root>
		</Field>
	);
});

// packages/solid/src/components/number-input/NumberInput.tsx
import type { NumberInputProps as CoreNumberInputProps } from "@temporal-ui/core/number-input";
import { type JSX, splitProps } from "solid-js";
import type { HTMLProps } from "@ark-ui/solid";
import { NumberInput as ArkNumberInput } from "@ark-ui/solid/number-input";
import { Field } from "../field";
import { ChevronDown, ChevronUp } from "lucide-solid";

export interface NumberInputProps
	extends CoreNumberInputProps<JSX.Element>,
		Omit<HTMLProps<"input">, "max" | "min" | "step" | "value"> {}

export function NumberInput(_props: NumberInputProps) {
	const [fieldProps, rootProps, inputProps] = splitProps(
		_props,
		["label", "hint", "error", "required", "readOnly", "disabled", "classes", "testId"],
		["startSection", "min", "max", "step", "onValueChange", "value", "defaultValue"],
	);

	return (
		<Field
			{...fieldProps}
			testId={fieldProps.testId ? `${fieldProps.testId}-field` : undefined}
		>
			<ArkNumberInput.Root
				min={rootProps.min}
				max={rootProps.max}
				step={rootProps.step}
				value={rootProps.value ? String(rootProps.value) : undefined}
				defaultValue={rootProps.defaultValue ? String(rootProps.defaultValue) : undefined}
				onValueChange={(details) => rootProps.onValueChange?.(details.valueAsNumber)}
				data-with-start-section={rootProps.startSection || undefined}
				data-testid={fieldProps.testId ? `${fieldProps.testId}--root` : undefined}
			>
				<ArkNumberInput.Control>
					{rootProps.startSection && (
						<div
							data-scope={"number-input"}
							data-part={"start-section"}
							data-testid={fieldProps.testId ? `${fieldProps.testId}--start-section` : undefined}
						>
							{rootProps.startSection}
						</div>
					)}
					<ArkNumberInput.Input
						{...inputProps}
						data-with-start-section={rootProps.startSection || undefined}
						data-testid={fieldProps.testId ? `${fieldProps.testId}--input` : undefined}
					/>
					<ArkNumberInput.IncrementTrigger>
						<ChevronUp size={16} />
					</ArkNumberInput.IncrementTrigger>
					<ArkNumberInput.DecrementTrigger>
						<ChevronDown size={16} />
					</ArkNumberInput.DecrementTrigger>
				</ArkNumberInput.Control>
			</ArkNumberInput.Root>
		</Field>
	);
}
