// packages/react/src/components/checkbox/Checkbox.tsx
import { Checkbox as ArkCheckbox } from "@ark-ui/react/checkbox";
import type { CheckboxProps as CoreCheckboxProps } from "@temporal-ui/core/checkbox";
import { CheckIcon } from "lucide-react";
import type React from "react";
import { forwardRef } from "react";
import { Field } from "../field";

export interface CheckboxProps extends CoreCheckboxProps<React.ReactNode> {}

export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>((props, ref) => {
	const {
		label,
		hint,
		error,
		required,
		readOnly,
		disabled,
		classes,
		defaultChecked,
		checked,
		onCheckedChange,
		testId,
		...rest
	} = props;

	return (
		<Field
			label={undefined}
			hint={hint}
			classes={classes}
			required={required}
			readOnly={readOnly}
			error={error}
			disabled={disabled}
			testId={testId ? `${testId}-field` : undefined}
		>
			<ArkCheckbox.Root
				ref={ref}
				defaultChecked={defaultChecked}
				checked={checked}
				onCheckedChange={(details) => onCheckedChange?.(details.checked)}
				data-testid={testId ? `${testId}--root` : undefined}
			>
				<ArkCheckbox.Control data-testid={testId ? `${testId}--control` : undefined}>
					<ArkCheckbox.Indicator data-testid={testId ? `${testId}--indicator` : undefined}>
						<CheckIcon />
					</ArkCheckbox.Indicator>
				</ArkCheckbox.Control>
				<ArkCheckbox.Label data-testid={testId ? `${testId}--label` : undefined}>
					{label}
				</ArkCheckbox.Label>
				<ArkCheckbox.HiddenInput
					data-testid={testId ? `${testId}--input` : undefined}
					{...rest}
				/>
			</ArkCheckbox.Root>
		</Field>
	);
});

// packages/solid/src/components/checkbox/Checkbox.tsx
import { Checkbox as ArkCheckbox } from "@ark-ui/solid/checkbox";
import type { CheckboxProps as CoreCheckboxProps } from "@temporal-ui/core/checkbox";
import type { JSX } from "solid-js";
import { splitProps } from "solid-js";
import { Field } from "../field";
import type { HTMLProps } from "@ark-ui/solid";
import { CheckIcon } from "lucide-solid";

export interface CheckboxProps
	extends CoreCheckboxProps<JSX.Element>,
		Omit<HTMLProps<"input">, "checked" | "onInput"> {}

export function Checkbox(_props: CheckboxProps) {
	const [fieldProps, rootProps] = splitProps(
		_props,
		["label", "hint", "error", "required", "readOnly", "disabled", "classes", "testId"],
		["defaultChecked", "checked", "onCheckedChange"],
	);

	return (
		<Field
			label={undefined}
			hint={fieldProps.hint}
			classes={fieldProps.classes}
			required={fieldProps.required}
			readOnly={fieldProps.readOnly}
			error={fieldProps.error}
			disabled={fieldProps.disabled}
			testId={fieldProps.testId ? `${fieldProps.testId}-field` : undefined}
		>
			<ArkCheckbox.Root
				defaultChecked={rootProps.defaultChecked}
				checked={rootProps.checked}
				onCheckedChange={(details) => rootProps.onCheckedChange?.(details.checked)}
				disabled={fieldProps.disabled}
				readOnly={fieldProps.readOnly}
				invalid={!!fieldProps.error}
				required={fieldProps.required}
				data-testid={fieldProps.testId ? `${fieldProps.testId}--root` : undefined}
			>
				<ArkCheckbox.Control
					data-testid={fieldProps.testId ? `${fieldProps.testId}--control` : undefined}
				>
					<ArkCheckbox.Indicator
						data-testid={
							fieldProps.testId ? `${fieldProps.testId}--indicator` : undefined
						}
					>
						<CheckIcon />
					</ArkCheckbox.Indicator>
				</ArkCheckbox.Control>
				{fieldProps.label && (
					<ArkCheckbox.Label
						data-testid={fieldProps.testId ? `${fieldProps.testId}--label` : undefined}
					>
						{fieldProps.label}
					</ArkCheckbox.Label>
				)}
				<ArkCheckbox.HiddenInput
					data-testid={fieldProps.testId ? `${fieldProps.testId}--input` : undefined}
				/>
			</ArkCheckbox.Root>
		</Field>
	);
}
