// packages/solid/src/components/field/Field.tsx
import { Field as ArkField } from "@ark-ui/solid/field";
import type { FieldProps as CoreFieldProps } from "@temporal-ui/core/field";
import { cx } from "@temporal-ui/core/utils/cx";
import type { JSX } from "solid-js";

export type FieldProps = CoreFieldProps<JSX.Element>;

export function Field(props: FieldProps) {

	return (
		<ArkField.Root
			class={cx("field-root", props.classes?.root)}
			invalid={!!props.error}
			disabled={props.disabled}
			readOnly={props.readOnly}
			required={props.required}
			data-testid={props.testId ? `${props.testId}--root` : undefined}
		>
			{props.label && (
				<ArkField.Label
					class={cx("field-label", props.classes?.label)}
					aria-disabled={props.disabled}
					data-testid={props.testId ? `${props.testId}--label` : undefined}
				>
					{props.label}
				</ArkField.Label>
			)}
			{props.hint && (
				<ArkField.HelperText
					class={cx("field-hint", props.classes?.hint)}
					aria-disabled={props.disabled}
					data-testid={props.testId ? `${props.testId}--hint` : undefined}
				>
					{props.hint}
				</ArkField.HelperText>
			)}
			{props.children}
			{props.error && (
				<ArkField.ErrorText
					class={cx("field-error", props.classes?.error)}
					data-testid={props.testId ? `${props.testId}--error` : undefined}
				>
					{props.error}
				</ArkField.ErrorText>
			)}
		</ArkField.Root>
	);
}

// packages/react/src/components/field/Field.tsx
import { Field as ArkField } from "@ark-ui/react/field";
import type { FieldProps as CoreFieldProps } from "@temporal-ui/core/field";
import { cx } from "@temporal-ui/core/utils/cx";
import type React from "react";

export type FieldProps = CoreFieldProps<React.ReactNode>;

export function Field(props: FieldProps) {
	const { label, hint, error, children, disabled, readOnly, required, classes, testId } = props;

	return (
		<ArkField.Root
			className={cx("field-root", classes?.root)}
			invalid={!!error}
			data-testid={testId ? `${testId}--root` : undefined}
			disabled={disabled}
			readOnly={readOnly}
			required={required}
		>
			{label && (
				<ArkField.Label
					className={cx("field-label", classes?.label)}
					data-testid={testId ? `${testId}--label` : undefined}
				>
					{label}
				</ArkField.Label>
			)}
			{hint && (
				<ArkField.HelperText
					className={cx("field-hint", classes?.hint)}
					aria-disabled={disabled}
					data-testid={testId ? `${testId}--hint` : undefined}
				>
					{hint}
				</ArkField.HelperText>
			)}
			{children}
			{error && (
				<ArkField.ErrorText
					className={cx("field-error", classes?.error)}
					data-testid={testId ? `${testId}--error` : undefined}
				>
					{error}
				</ArkField.ErrorText>
			)}
		</ArkField.Root>
	);
}
