// packages/react/src/components/toggle/Toggle.tsx
import { Toggle as ArkToggle } from "@ark-ui/react/toggle";
import type { ToggleProps as CoreToggleProps } from "@temporal-ui/core/toggle";
import type React from "react";
import { forwardRef } from "react";

export interface ToggleProps
	extends CoreToggleProps<React.ReactNode>,
		Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "children" | "disabled"> {}

export const Toggle = forwardRef<HTMLButtonElement, ToggleProps>((props, ref) => {
	const { pressed, defaultPressed, onPressedChange, disabled, className, children, testId, ...rest } = props;

	return (
		<ArkToggle.Root
			ref={ref}
			pressed={pressed}
			defaultPressed={defaultPressed}
			onPressedChange={onPressedChange}
			disabled={disabled}
			className={className}
			data-testid={testId}
			{...rest}
		>
			{children}
		</ArkToggle.Root>
	);
});

export const ToggleIndicator = ArkToggle.Indicator;

// packages/solid/src/components/toggle/Toggle.tsx
import { Toggle as ArkToggle } from "@ark-ui/solid/toggle";
import type { ToggleProps as CoreToggleProps } from "@temporal-ui/core/toggle";
import type { JSX } from "solid-js";
import { splitProps } from "solid-js";

export interface ToggleProps
	extends CoreToggleProps<JSX.Element>,
		Omit<JSX.ButtonHTMLAttributes<HTMLButtonElement>, "children" | "disabled"> {}

export function Toggle(props: ToggleProps) {
	const [local, rest] = splitProps(props, [
		"pressed",
		"defaultPressed",
		"onPressedChange",
		"disabled",
		"class",
		"children",
		"testId",
	]);

	return (
		<ArkToggle.Root
			pressed={local.pressed}
			defaultPressed={local.defaultPressed}
			onPressedChange={local.onPressedChange}
			disabled={local.disabled}
			class={local.class}
			data-testid={local.testId}
			{...rest}
		>
			{local.children}
		</ArkToggle.Root>
	);
}

export const ToggleIndicator = ArkToggle.Indicator;
