// packages/react/src/components/toggle/ToggleGroup.tsx
import { ToggleGroup as ArkToggleGroup } from "@ark-ui/react/toggle-group";
import type React from "react";

export interface ToggleGroupProps extends React.ComponentProps<typeof ArkToggleGroup.Root> {
	testId?: string;
}

export interface ToggleGroupItemProps extends React.ComponentProps<typeof ArkToggleGroup.Item> {}

export function ToggleGroup(props: ToggleGroupProps) {
	const { testId, ...rest } = props;

	return (
		<ArkToggleGroup.Root
			data-testid={testId}
			{...rest}
		/>
	);
}

export const ToggleGroupItem = ArkToggleGroup.Item;

// packages/solid/src/components/toggle/ToggleGroup.tsx
import { ToggleGroup as ArkToggleGroup } from "@ark-ui/solid/toggle-group";
import type { ComponentProps } from "solid-js";
import { splitProps } from "solid-js";

export interface ToggleGroupProps extends ComponentProps<typeof ArkToggleGroup.Root> {
	testId?: string;
}

export interface ToggleGroupItemProps extends ComponentProps<typeof ArkToggleGroup.Item> {}

export function ToggleGroup(props: ToggleGroupProps) {
	const [local, rest] = splitProps(props, ["testId"]);

	return (
		<ArkToggleGroup.Root
			data-testid={local.testId}
			{...rest}
		/>
	);
}

export const ToggleGroupItem = ArkToggleGroup.Item;
