// packages/react/src/components/popover/PopoverContent.tsx
import { Box, type BoxProps } from "../box";
import { Popover as ArkPopover } from "@ark-ui/react/popover";

export interface PopoverContentProps extends BoxProps {
	title?: string;
	description?: string;
	classes?: {
		content?: string;
		title?: string;
		description?: string;
	};
}

export function PopoverContent(props: PopoverContentProps) {
	const { title, description, classes, children, testId, ...boxProps } = props;

	return (
		<ArkPopover.Positioner data-testid={testId ? `${testId}--positioner` : undefined}>
			<ArkPopover.Content data-testid={testId ? `${testId}--content` : undefined}>
				<Box
					{...boxProps}
					className={classes?.content}
				>
					{title && (
						<ArkPopover.Title
							className={classes?.title}
							data-testid={testId ? `${testId}--title` : undefined}
						>
							{title}
						</ArkPopover.Title>
					)}
					{description && (
						<ArkPopover.Description
							className={classes?.description}
							data-testid={testId ? `${testId}--description` : undefined}
						>
							{description}
						</ArkPopover.Description>
					)}
					{children}
				</Box>
			</ArkPopover.Content>
		</ArkPopover.Positioner>
	);
}

// packages/solid/src/components/popover/PopoverContent.tsx
import { Popover as ArkPopover } from "@ark-ui/solid/popover";
import { splitProps } from "solid-js";
import { Box, type BoxProps } from "../box";

export interface PopoverContentProps extends BoxProps {
	title?: string;
	description?: string;
	classes?: {
		content?: string;
		title?: string;
		description?: string;
	};
}

export function PopoverContent(props: PopoverContentProps) {
	const [contentProps, boxProps] = splitProps(props, [
		"title",
		"description",
		"classes",
		"children",
		"testId",
	]);

	return (
		<ArkPopover.Positioner
			data-testid={props.testId ? `${props.testId}--positioner` : undefined}
		>
			<ArkPopover.Content data-testid={props.testId ? `${props.testId}--content` : undefined}>
				<Box {...boxProps}>
					{contentProps.title && (
						<ArkPopover.Title
							class={contentProps.classes?.title}
							data-testid={
								contentProps.testId ? `${contentProps.testId}--title` : undefined
							}
						>
							{contentProps.title}
						</ArkPopover.Title>
					)}
					{contentProps.description && (
						<ArkPopover.Description
							class={contentProps.classes?.description}
							data-testid={
								contentProps.testId
									? `${contentProps.testId}--description`
									: undefined
							}
						>
							{contentProps.description}
						</ArkPopover.Description>
					)}
					{contentProps.children}
				</Box>
			</ArkPopover.Content>
		</ArkPopover.Positioner>
	);
}
