// packages/react/src/components/tooltip/Tooltip.tsx
import type { TooltipProps as CoreTooltipProps } from "@temporal-ui/core/tooltip";
import { Tooltip as ArkTooltip } from "@ark-ui/react/tooltip";
import type React from "react";
import { Portal } from "@ark-ui/react";
import { TooltipContent } from "./TooltipContent";
import { testId as testIdFn } from "@temporal-ui/core/utils/string";

export interface TooltipProps
	extends CoreTooltipProps<React.ReactNode>,
		Omit<React.ComponentProps<typeof ArkTooltip.Root>, "onOpenChange"> {
	trigger?: React.ReactNode;
}

export function Tooltip(props: TooltipProps) {
	const {
		trigger,
		portal = true,
		lazyMount = true,
		unmountOnExit = true,
		position,
		testId,
		className,
		classes,
		showArrow = false,
		children,
		onOpenChange,
		...rootProps
	} = props;

	const tid = testIdFn(testId);

	const content = (
		<TooltipContent
			testId={testId}
			className={className}
			classes={classes}
			showArrow={showArrow}
		>
			{children}
		</TooltipContent>
	);

	return (
		<ArkTooltip.Root
			portalled={portal}
			lazyMount={lazyMount}
			unmountOnExit={unmountOnExit}
			{...rootProps}
			onOpenChange={(details) => onOpenChange?.(details.open)}
			positioning={position}
			data-testid={tid("--root")}
		>
			{trigger && (
				<ArkTooltip.Trigger
					asChild
					className={props.classes?.trigger}
					data-testid={tid("--trigger")}
				>
					{trigger}
				</ArkTooltip.Trigger>
			)}
			{portal ? <Portal>{content}</Portal> : content}
		</ArkTooltip.Root>
	);
}

// packages/solid/src/components/tooltip/Tooltip.tsx
import { Tooltip as ArkTooltip } from "@ark-ui/solid/tooltip";
import type { TooltipProps as CoreTooltipProps } from "@temporal-ui/core/tooltip";
import { testId } from "@temporal-ui/core/utils/string";
import { mergeProps, Show, splitProps, type ComponentProps, type JSX } from "solid-js";
import { Portal } from "solid-js/web";
import { TooltipContent as TemporalTooltipContent } from "./TooltipContent";

export interface TooltipProps
	extends CoreTooltipProps<JSX.Element>,
		Omit<ComponentProps<typeof ArkTooltip.Root>, "onOpenChange"> {
	trigger?: (props: Record<string, unknown>) => JSX.Element;
}

export function Tooltip(props: TooltipProps) {
	const [localProps, rootProps] = splitProps(
		mergeProps({ portal: true, lazyMount: true, unmountOnExit: true }, props),
		["trigger", "portal", "testId", "position", "onOpenChange", "classes", "className", "children", "showArrow"],
	);

	const tid = testId(localProps.testId);

	return (
		<ArkTooltip.Root
			{...rootProps}
			portalled={localProps.portal}
			onOpenChange={(details) => localProps.onOpenChange?.(details.open)}
			positioning={localProps.position}
			data-testid={tid("--root")}
		>
			<Show when={localProps.trigger}>
				<ArkTooltip.Trigger
					asChild={(triggerProps) => localProps.trigger?.({ ...triggerProps() })}
					class={localProps.classes?.trigger}
					data-testid={tid("--trigger")}
				/>
			</Show>
			<Show when={localProps.portal}>
				<Portal>
					<TemporalTooltipContent
						testId={localProps.testId}
						className={localProps.className}
						classes={localProps.classes}
						showArrow={localProps.showArrow}
						children={localProps.children}
					/>
				</Portal>
			</Show>
			<Show when={!localProps.portal}>
				<TemporalTooltipContent
					testId={localProps.testId}
					className={localProps.className}
					classes={localProps.classes}
					showArrow={localProps.showArrow}
					children={localProps.children}
				/>
			</Show>
		</ArkTooltip.Root>
	);
}
