// packages/react/src/components/accordion/Accordion.tsx
import { type AccordionRootBaseProps, Accordion as ArkAccordion } from "@ark-ui/react/accordion";
import type { AccordionProps as CoreAccordionProps } from "@temporal-ui/core/accordion";

export interface AccordionProps
	extends CoreAccordionProps<React.ReactNode>,
		Omit<AccordionRootBaseProps, "onValueChange"> {}

export function Accordion(props: AccordionProps) {
	const {
		variant = "default",
		className,
		testId,
		onValueChange,
		collapsible = true,
		lazyMount = true,
		unmountOnExit = true,
		...rest
	} = props;

	return (
		<ArkAccordion.Root
			className={className}
			data-testid={testId}
			data-variant={variant}
			collapsible={collapsible}
			lazyMount={lazyMount}
			unmountOnExit={unmountOnExit}
			onValueChange={(details) => onValueChange?.(details.value)}
			{...rest}
		/>
	);
}

export const AccordionItem = ArkAccordion.Item;
export const AccordionItemTrigger = ArkAccordion.ItemTrigger;
export const AccordionItemContent = ArkAccordion.ItemContent;
export const AccordionItemIndicator = ArkAccordion.ItemIndicator;

// packages/solid/src/components/accordion/Accordion.tsx
import { type AccordionRootBaseProps, Accordion as ArkAccordion } from "@ark-ui/solid/accordion";
import type { AccordionProps as CoreAccordionProps } from "@temporal-ui/core/accordion";
import { mergeProps, splitProps, type JSX } from "solid-js";

export interface AccordionProps
	extends CoreAccordionProps<JSX.Element>,
		Omit<AccordionRootBaseProps, "onValueChange"> {}

export function Accordion(props: AccordionProps) {
	const merged = mergeProps({ variant: "default", collapsible: true, lazyMount: true, unmountOnExit: true }, props);
	const [controlProps, rootProps] = splitProps(merged, ["variant", "className", "testId", "onValueChange"]);

	return (
		<ArkAccordion.Root
			class={controlProps.className}
			data-testid={controlProps.testId}
			data-variant={controlProps.variant}
			onValueChange={(details) => controlProps.onValueChange?.(details.value)}
			{...rootProps}
		/>
	);
}

export const AccordionItem = ArkAccordion.Item;
export const AccordionItemTrigger = ArkAccordion.ItemTrigger;
export const AccordionItemContent = ArkAccordion.ItemContent;
export const AccordionItemIndicator = ArkAccordion.ItemIndicator;
