// packages/react/src/components/avatar/Avatar.tsx
import { Avatar as ArkAvatar } from "@ark-ui/react/avatar";
import { type AvatarProps as AvatarPropsCore, cx, getInitials } from "@temporal-ui/core";
import { UserIcon } from "lucide-react";
import { forwardRef } from "react";

export interface AvatarProps extends AvatarPropsCore {}

export const Avatar = forwardRef<HTMLDivElement, AvatarProps & ArkAvatar.RootProps>((props, ref) => {
	const { name, src, className, ...rootProps } = props;
	const size = props.size !== "md" ? props.size : "";
	const baseClass = [ "avatar", size ].filter(Boolean).join("-");
	return (
		<ArkAvatar.Root
			ref={ref}
			className={cx(baseClass, className)}
			{...rootProps}
		>
			<ArkAvatar.Fallback>{getInitials(name) || <UserIcon />}</ArkAvatar.Fallback>
			<ArkAvatar.Image src={src} alt={name} />
		</ArkAvatar.Root>
	);
});

// packages/solid/src/components/avatar/Avatar.tsx
import { Avatar as ArkAvatar } from "@ark-ui/solid/avatar";
import { type AvatarProps as AvatarPropsCore, cx, getInitials } from "@temporal-ui/core";
import { UserIcon } from "lucide-solid";
import { Show, splitProps } from "solid-js";

export interface AvatarProps extends AvatarPropsCore {

}

export const Avatar = (props: AvatarProps & ArkAvatar.RootProps) => {
	const [localProps, rootProps] = splitProps(props, ['name', 'src', 'size', 'class'])
	const size = localProps.size !== "md" ? localProps.size : "";
	const baseClass = ["avatar", size].filter(Boolean).join("-");
	return (
		<ArkAvatar.Root {...rootProps} class={cx(baseClass, localProps.class)}>
			<ArkAvatar.Fallback>
				<Show when={localProps.name} fallback={<UserIcon />}>
					{getInitials(localProps.name)}
				</Show>
			</ArkAvatar.Fallback>
			<ArkAvatar.Image src={localProps.src} alt={localProps.name} />
		</ArkAvatar.Root>
	)
}
